---

- name: Copy dnf.conf
  ansible.builtin.copy:
    src: files/dnf.conf
    dest: /etc/dnf/dnf.conf
    mode: '644'
    owner: root
    group: root
  become: true
  become_user: root
  tags:
    - configuration
