---

- name: Configure git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      scope: global
      value: "{{ git_username }}"
    - name: user.email
      scope: global
      value: "{{ git_email }}"
    - name: core.editor
      scope: global
      value: "{{ git_editor }}"
    - name: init.defaultBranch
      scope: global
      value: "{{ git_default_branch }}"
  become: true
  become_user: "{{ ansible_user_id }}"
