---

- name: Modify dconf settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value |string }}"
    state: present
  loop:
    - key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
    - key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - user
    - configuration
