---

- name: Ensure "~/.ssh" directory exists
  ansible.builtin.file:
    dest: "/home/{{ ansible_user_id }}/.ssh"
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory

- name: Copy ssh config
  ansible.builtin.copy:
    src: files/ssh/config
    dest: "/home/{{ ansible_user_id }}/.ssh/config"
    mode: '0400'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

