---

- name: Set up tmux configuration
  block:
    - name: Ensure "~/.config/tmux" directory exists
      ansible.builtin.file:
        dest: "/home/{{ ansible_user_id }}/.config/tmux"
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory

    - name: Copy tmux configuration files and tmuxp files
      ansible.builtin.copy:
        src: files/config/tmux/
        dest: "/home/{{ ansible_user_id }}/.config/tmux/"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
