---

- name: Add brave-browser repo
  ansible.builtin.yum_repository:
    name: brave-browser
    description: Brave Browser Release Channel
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    gpgcheck: true
    enabled: true
    skip_if_unavailable: true
  become: true
  become_user: root
