---

- name: Enable copr repos
  community.general.copr:
    host: "{{ item.host }}"
    name: "{{ item.name }}"
    state: enabled
  loop:
    - host: copr.fedorainfracloud.org
      name: yuezk/globalprotect-openconnect
  become: true
  become_user: root
