---

- name: Import rpm keys
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    state: present
  loop:
    - key: https://downloads.1password.com/linux/keys/1password.asc
    - key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    - key: https://packages.microsoft.com/keys/microsoft.asc
    - key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  become: true
  become_user: root
  tags:
    - repositories
