---

- name: Install extra packages
  ansible.builtin.dnf:
    name:
      - dconf
      - gnome-tweaks

      - 1password
      - brave-browser
      - steam

      - bash
      - bash-completion
      - zsh
      - fish

      - vim
      - neovim
      - emacs
      - code

      - texlive-scheme-full

      - llvm
      - clang
      - clang-devel

      - java-latest-openjdk
      - java-latest-openjdk-devel

      - nodejs
      - nodejs-devel
      - npm

      - ruby
      - ruby-devel

      - python
      - python-devel
      - python-flake8
      - python-black
      - python-isort
      - python-psutil
      - python-tmuxp
      - "{{ python_nvim }}"

      - tmux
      - ripgrep
      - "{{ fd_find }}"
      - libtree-sitter
    state: latest
  become: true
  become_user: root
  tags:
    - packages
