---

- name: Install and set up flatpak
  block:
    - name: Install flatpak package
      ansible.builtin.dnf:
        name: flatpak
        state: latest
      become: true
      become_user: root
    
    - name: Add flathub repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
      become: true
      become_user: "{{ ansible_user_id }}"
  tags:
    - flatpak
    - packages
