---

# package groups
- import_tasks: group/core.yaml
# fedora repos
- import_tasks: flatpak.yaml
- import_tasks: devel.yaml
- import_tasks: texlive.yaml
- import_tasks: editors.yaml
- import_tasks: steam.yaml
- import_tasks: tweaks.yaml
# external repo
- import_tasks: 1password.yaml
- import_tasks: code.yaml
- import_tasks: brave-browser.yaml
