---

- import_tasks: group/core.yaml
- import_tasks: group/devel.yaml
- import_tasks: texlive.yaml
- import_tasks: 1password.yaml
- import_tasks: code.yaml
- import_tasks: brave-browser.yaml
- import_tasks: emacs.yaml
- import_tasks: steam.yaml
- import_tasks: helpers/cleanup.yaml
