---

# {{{ group_pkgs
group_pkgs:
  - "@core"
  - "@development tools"
  - "@c development tools and libraries"
  - "@rpm development tools"
  - "@virtualization"
# }}}

# {{{ extra_pkgs
extra_pkgs:
  # {{{ Gnome & GTK
  - gnome-tweaks
  # }}}

  # {{{ GUI Applications
  - code
  - 1password
  - "{{ firefox }}"
  - brave-browser
  - steam
  - "{{ libreoffice }}"
  # }}}

  # {{{ CLI Tools
  - 1password-cli
  - htop
  - bpytop
  - fzf
  - gawk
  - bat
  - most
  - sed
  # }}}

  # {{{ Technical Writing
  - texlive-scheme-full
  # }}}

  # {{{ Development
  # {{{ C/C++
  - llvm
  - clang
  - clang-devel
  # }}}

  # {{{ Java
  - java-latest-openjdk
  - java-latest-openjdk-devel
  # }}}

  # {{{ Ruby
  - ruby
  - ruby-devel
  # }}}

  # {{{ Python
  - python
  - python-devel
  - python-flake8
  - python-black
  - python-isort
  # }}}
  # }}}
# }}}

# {{{ font_pkgs
font_pkgs:
  - "{{ adobe_source_code_pro_fonts }}"
  - "{{ dejavu_fonts }}"
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts
  - powerline-fonts
# }}}

# {{{ unwanted_pkgs
unwanted_pkgs:
  - gnome-tour
# }}}

# vim: fdm=marker ft=yaml.ansible
