---

- name: Install tmux packages
  become: true
  ansible.builtin.package:
    name: "{{ tmux_packages }}"
    state: present

- name: Install tmuxp through pip
  when: ansible_facts["distribution"] == "OpenSuse"
  ansible.builtin.pip:
    name: tmuxp
    extra_args: --user

# vim: ft=yaml.ansible
