---

- name: Clone pavalos6401/nvim repo for neovim
  ansible.builtin.git:
    repo: https://github.com/pavalos6401/nvim.git
    dest: "{{ nvim_dir }}"

- name: Clone pavalos6401/nvim repo (legacy) for vim
  ansible.builtin.git:
    repo: https://github.com/pavalos6401/nvim.git
    dest: "{{ vim_dir }}"
    version: legacy

- name: Symlink init.vim to vimrc
  ansible.builtin.file:
    src: "{{ vim_dir }}/init.vim"
    dest: "{{ vimrc }}"
    state: link

# vim: ft=yaml.ansible
