---

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0744'
    state: directory
  loop:
    - path: "{{ nvim_dir }}"
    - path: "{{ vim_dir }}"
    - path: "{{ vimwiki_dir }}"

- name: Copy configuration files
  ansible.builtin.copy:
    src: nvim/
    dest: "{{ nvim_dir }}/"
    mode: '0644'
    directory_mode: '0744'

- name: Symlink configuration files for vim
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: "{{ nvim_dir }}/init.vim"
      dest: "{{ vimrc }}"
    - src: "{{ nvim_dir }}/config"
      dest: "{{ vim_dir }}/config"
    - src: "{{ nvim_dir }}/coc-settings.json"
      dest: "{{ vim_dir }}/coc-settings.json"

# vim: ft=yaml.ansible
